# Generated by Django 3.2.5 on 2021-08-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OneSubjectQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('physics', 'Physics'), ('maths', 'Maths'), ('chem', 'Chemistry')], max_length=50)),
                ('time', models.IntegerField(help_text='(In Minutes)', max_length=50)),
                ('no_of_ques', models.IntegerField(max_length=100)),
            ],
            options={
                'verbose_name': 'One Subject Quiz',
                'verbose_name_plural': 'One Subject Quizes',
            },
        ),
    ]
