# Generated by Django 3.2.5 on 2021-07-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuesMcq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('option_1', models.CharField(max_length=500)),
                ('option_2', models.CharField(max_length=500)),
                ('option_3', models.CharField(max_length=500)),
                ('option_4', models.CharField(max_length=500)),
                ('answer', models.CharField(choices=[('option_1', 'option 1'), ('option_2', 'option 2'), ('option_3', 'option 3'), ('option_4', 'option 4')], max_length=50)),
                ('subject', models.CharField(choices=[('PHY', 'physics'), ('MTH', 'maths'), ('CHEM', 'chemistry')], max_length=50)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('publish', models.BooleanField(default=True)),
            ],
        ),
    ]
