# Generated by Django 3.2.5 on 2021-07-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quesmcq',
            name='answer',
            field=models.CharField(choices=[(models.CharField(max_length=500), 'option 1'), (models.CharField(max_length=500), 'option 2'), (models.CharField(max_length=500), 'option 3'), (models.CharField(max_length=500), 'option 4')], max_length=50),
        ),
    ]
