# Generated by Django 3.2.5 on 2021-07-30 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20210729_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quesinttype',
            name='answer',
        ),
        migrations.AddField(
            model_name='quesinttype',
            name='difficulty_level',
            field=models.IntegerField(default=1, help_text='Take Range from 1 to 5 only'),
        ),
        migrations.AddField(
            model_name='quesmcq',
            name='difficulty_level',
            field=models.IntegerField(default=1, help_text='Take Range from 1 to 5 only'),
        ),
    ]
