# Generated by Django 3.2.5 on 2021-07-30 06:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20210730_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quesinttype',
            name='difficulty_level',
            field=models.IntegerField(default=1, help_text='Take Range from 1 to 5 only', validators=[django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='quesmcq',
            name='difficulty_level',
            field=models.IntegerField(default=1, help_text='Take Range from 1 to 5 only', validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
