# Generated by Django 3.2.5 on 2021-07-30 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_auto_20210730_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quesmcq',
            name='subject',
            field=models.CharField(choices=[('physics', 'Physics'), ('maths', 'Maths'), ('chem', 'Chemistry')], max_length=50),
        ),
    ]
