# Generated by Django 3.2.5 on 2021-07-30 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_alter_quesinttype_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quesinttype',
            options={'verbose_name': 'Numeric Type Question'},
        ),
        migrations.AlterModelOptions(
            name='quesmcq',
            options={'verbose_name': 'MCQ type Question'},
        ),
    ]
