# Generated by Django 3.2.5 on 2021-08-02 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20210802_1932'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
